name: Node.js CI checking if server starts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: instaling
      working-directory: ./server 
      run: npm i
    - name: starting server
      working-directory: ./server
      run: npm start
      env:
        CI: true
        SECRET: secretwhatever
        DATABASE_URL: postgres://nviwmkcg:4-G6tFZ1xeDNz_W6f9C-qWQTJo8sq6Ww@drona.db.elephantsql.com:5432/nviwmkcg